development: &development
  adapter: postgresql
  encoding: utf8
  database: teado_development
  username:
  password:

test:
  <<: *development
  database: teado_test

cucumber:
  <<: *development
  database: teado_cucumber

production:
  <<: *development
  database: teado_production

